<?php

namespace AppBundle\Repository;

/**
 * ExcerciseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExcerciseRepository extends \Doctrine\ORM\EntityRepository
{
}
