# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
     test.service.notification.class: AppBundle\Service\NotificationService

services:
    notification:
        class: %test.service.notification.class%
        arguments: ["@session"]